In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,7,8])

In [3]:
myarr

array([3, 6, 7, 8])

In [4]:
myarr2 = np.array([[3,5,7,9]],np.int8)

In [5]:
myarr2[0,1]

5

In [7]:
myarr2.shape

(1, 4)

In [8]:
myarr2.dtype

dtype('int8')

In [9]:
myarr2[0,1] = 11

In [10]:
myarr2

array([[ 3, 11,  7,  9]], dtype=int8)

In [11]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({3,5,8})

array({8, 3, 5}, dtype=object)

In [17]:
zeros = np.zeros((3,7))

In [18]:
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,40,8)

In [25]:
lspace

array([ 1.        ,  6.57142857, 12.14285714, 17.71428571, 23.28571429,
       28.85714286, 34.42857143, 40.        ])

In [26]:
emp = np.empty((4,7))

In [27]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.37961913e-306, 1.42417900e-306, 1.78019082e-306,
        1.37961913e-306],
       [6.23057349e-307, 1.02360935e-306, 1.69120416e-306,
        1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        1.27946076e-307],
       [6.23037657e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 3.56036603e-307,
        1.37961641e-306],
       [1.37961302e-306, 1.11259940e-306, 1.60219035e-306,
        1.11261570e-306, 1.06811354e-306, 8.34448533e-308,
        3.91792476e-317]])

In [34]:
ide = np.identity(55)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
arr = np.arange(99)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
ar.sum(axis = 0)

array([12, 15, 18])

In [44]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar.flat

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [48]:
ar.size

9

In [49]:
ar.nbytes

36

In [50]:
ar.ndim

2

In [53]:
one = np.array([231,211,323,51])

In [54]:
one.argmax()

2

In [55]:
one.argmin()

3

In [56]:
one.argsort()

array([3, 1, 0, 2], dtype=int32)

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int32)

In [60]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int32)

In [61]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [64]:
ar2 = np.array([[1, 3, 6],
       [2, 5, 8],
       [4, 2, 9]])

In [66]:
ar + ar2

array([[ 2,  5,  9],
       [ 6, 10, 14],
       [11, 10, 18]])

In [67]:
ar * ar2

array([[ 1,  6, 18],
       [ 8, 25, 48],
       [28, 16, 81]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [70]:
ar.sum()

45

In [71]:
ar.max()

9

In [72]:
ar.min()

1

In [73]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int32), array([2, 0, 1, 2], dtype=int32))

In [74]:
np.count_nonzero(ar)

9

In [75]:
import sys

In [76]:
ch_ar = [6,7,3,1,8]

In [77]:
np_ar = np.array(ch_ar)

In [78]:
sys.getsizeof(1) * len(ch_ar)

70

In [80]:
np_ar.itemsize * np_ar.size

20